#!/bin/bash
# scripts/switch-llvm-version.sh
#
# Auto-detects the system LLVM version and updates .cargo/config.toml + Cargo.toml
# to use the correct llvm-sys version. Eliminates manual editing when switching
# between build server (LLVM 19) and user environment (LLVM 21).
#
# Usage:
#   bash scripts/switch-llvm-version.sh          # auto-detect
#   bash scripts/switch-llvm-version.sh 19       # force LLVM 19
#   bash scripts/switch-llvm-version.sh 21       # force LLVM 21
#
# After running, build with:
#   cargo build --lib --features llvm-backend

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CARGO_TOML="$PROJECT_ROOT/Cargo.toml"
CARGO_CONFIG="$PROJECT_ROOT/.cargo/config.toml"

# ── Determine target LLVM version ────────────────────────────────────────────

FORCE_VERSION="${1:-}"

if [ -n "$FORCE_VERSION" ]; then
    LLVM_MAJOR="$FORCE_VERSION"
    echo "Forced LLVM version: $LLVM_MAJOR"
else
    # Auto-detect: check system llvm-config first
    if command -v llvm-config &> /dev/null; then
        LLVM_FULL=$(llvm-config --version)
        LLVM_MAJOR=$(echo "$LLVM_FULL" | cut -d. -f1)
        LLVM_PREFIX=$(llvm-config --prefix)
        echo "Detected system LLVM: $LLVM_FULL (major=$LLVM_MAJOR, prefix=$LLVM_PREFIX)"
    elif [ -x /tmp/llvm-19-prefix/bin/llvm-config ]; then
        LLVM_MAJOR=19
        LLVM_PREFIX="/tmp/llvm-19-prefix"
        echo "Detected build-server LLVM 19 at $LLVM_PREFIX"
    else
        echo "ERROR: No llvm-config found. Run 'source scripts/setup-llvm-env.sh' first."
        exit 1
    fi
fi

# Map major version → llvm-sys crate version + env var suffix
case "$LLVM_MAJOR" in
    18) LLVM_SYS_VER="181" ;;
    19) LLVM_SYS_VER="191" ;;
    20) LLVM_SYS_VER="201" ;;
    21) LLVM_SYS_VER="211" ;;
    22) LLVM_SYS_VER="221" ;;
    *)  echo "ERROR: Unsupported LLVM version: $LLVM_MAJOR (supported: 18-22)"; exit 1 ;;
esac

# Determine prefix
if [ -z "${LLVM_PREFIX:-}" ]; then
    if command -v llvm-config &> /dev/null; then
        LLVM_PREFIX=$(llvm-config --prefix)
    elif [ "$LLVM_MAJOR" = "19" ]; then
        LLVM_PREFIX="/tmp/llvm-19-prefix"
    else
        echo "ERROR: Cannot determine LLVM prefix for version $LLVM_MAJOR"
        exit 1
    fi
fi

echo "LLVM major version : $LLVM_MAJOR"
echo "llvm-sys crate ver : $LLVM_SYS_VER"
echo "LLVM prefix         : $LLVM_PREFIX"
echo ""

# ── Update .cargo/config.toml ────────────────────────────────────────────────

echo "Updating $CARGO_CONFIG ..."

cat > "$CARGO_CONFIG" << EOF
# Auto-generated by scripts/switch-llvm-version.sh
# LLVM version: $LLVM_MAJOR (llvm-sys $LLVM_SYS_VER)
# Re-run: bash scripts/switch-llvm-version.sh

[env]
LLVM_SYS_${LLVM_SYS_VER}_PREFIX = "$LLVM_PREFIX"
LLVM_LINK_SHARED = "1"
EOF

echo "  → LLVM_SYS_${LLVM_SYS_VER}_PREFIX = $LLVM_PREFIX"
echo "  → LLVM_LINK_SHARED = 1"

# ── Update Cargo.toml llvm-sys version ───────────────────────────────────────

echo "Updating $CARGO_TOML ..."

# Use Python for robust TOML editing (sed is fragile with version strings)
python3 << PYEOF
import re

with open("$CARGO_TOML", "r") as f:
    content = f.read()

# Replace llvm-sys version = "XXX" with the correct version
new_ver = "$LLVM_SYS_VER"
content = re.sub(
    r'(\[dependencies\.llvm-sys\]\s*\nversion\s*=\s*)"[0-9]+"',
    r'\1"' + new_ver + '"',
    content
)

with open("$CARGO_TOML", "w") as f:
    f.write(content)

print(f"  → llvm-sys version = \"{new_ver}\"")
PYEOF

echo ""
echo "✅ LLVM version switched to $LLVM_MAJOR (llvm-sys $LLVM_SYS_VER)"
echo ""
echo "Next steps:"
echo "  cargo clean"
echo "  cargo build --lib --features llvm-backend"
echo "  cargo test --test all_tests"
